### ISSUE TITLE
"transport error - Premature End of File (socket) while reading headers" after upgrading Remote Wiki to PHP 8.1

### ISSUE THREAD

**Issue by eduardomozart** [splitbrain/dokuwiki-plugin-sync#68]
I`d upgraded my Local and Remote Wikis to PHP 8.1 and started receiving the following error when selecting a Wiki profile and clicking on "Select" button into the Remote Wiki:

````
Failed to talk to remote wiki. Make sure the remote wiki allows XMLRPC requests and that you set up the endpoint URL correctly. transport error - Premature End of File (socket) while reading headers
````

After downgrading the Remote Wiki to PHP 7.4, the plugin worked as expected.

**Comment by mightymt** [comment]
I get the same error. My local wiki is on PHP 7.4 (DokuWiki's MicroApache) and the remote server is using PHP 8.1.

**Comment by cziehr** [comment]
I get the same error.

Both wikis are on PHP 7.4 (Apache) on Docker, both are on release 2024-02-06a "Kaos". On the server side, xmlrpc is activated, and not restricted to a specific user.

xmlrpc is installed and activated. With a xmlrpc-test-script from the internet, it was possible to establish a connection and transmit data.

On the first try, I typed a wrong password in the sync-profile, and got an error that my credentials are wrong. When I typed in the correct password, I got the error message which is in the topic.

**Comment by eduardomozart** [comment]
I was able to overcome this issue by using https://github.com/splitbrain/dokuwiki-plugin-sync/tree/refactor that is the new upcoming version of this plugin. It's still a little bug and has some issues. Most of them (at least the critical ones) were fixed by this PR: https://github.com/splitbrain/dokuwiki-plugin-sync/pull/74 that you'll need to apply after using the refactor. All plugin development is now moved to there, according to splitbrain (main plugin developer).

**Comment by cziehr** [comment]
Thank you for your hint and that you provide a PR. I've tried to use your version, but when I try to start the synchronization after choosing the profile, the page underneath the synchronization headline remains empty and nothing happens (see attached screenshot).

![Bildschirmfoto zu 2024-06-30 14-09-47](https://github.com/splitbrain/dokuwiki-plugin-sync/assets/580647/fadd59db-0375-4cc8-b93f-a1f75228bb87)

Thanks again for your help!

**Comment by eduardomozart** [comment]
Can you provide your local Wiki logs on Manage > View Logs? On your remote wiki, which PHP version you're using? The server side seems to be troublesome on PHP 8+ yet. My remote wiki still runs PHP 7 because of that.

**Comment by tokubi** [comment]
Unfortunately, I too have been struggling with the same problem for a long time.

From the synchronization behavior I can observe it seems that synchronization does not work with PHP version 8 and higher. To verify this, I set up two identical environments with two instances of Dokuwiki using two independent Raspberry Pi 5, both in the same local network segment. Here is the configuration:

```
Revision        : d04170
Model           : Raspberry Pi 5 Model B Rev 1.0
 
Linux: Linux version 6.6.51+rpt-rpi-2712 (serge@raspberrypi.com)
Build: (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40)
Release  : 6.6.51+rpt-rpi-2712
Version  : #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) 
 
PHP 8.2.24 (cli) (built: Sep 27 2024 04:16:10) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.24, Copyright (c) Zend Technologies with Zend OPcache v8.2.24, Copyright (c), by Zend Technologies
 
Dokuwiki:
Release 2024-02-06b "Kaos"
 
Apache:
Server version: Apache/2.4.62 (Debian)
Server built:   2024-10-04T15:21:08
```

Both Dokuwiki's have synchronization enabled and configured correctly.

The test scenario consists of synchronizing the playground namespace between the two dokuwikies.

If we try to select a synchronization profile on the synchronization page, this error occurs:

_Failed to talk to remote wiki. Make sure the remote wiki allows XMLRPC requests and that you set up the endpoint URL correctly. transport error - Premature End of File (socket) while reading headers_

Everything should be clearly visible from the screenshots:

![024-11-10_dokuwiki_1731254538](https://github.com/user-attachments/assets/7ea6a9ae-41bc-42c5-b372-13f1e36750f0)

![024-11-10_dokuwiki_1731254543](https://github.com/user-attachments/assets/bcf81f40-650d-439b-b375-0a86692cf173)

However, the strange thing is that this error does not always occur. By retrying the profile selection, in one case out of many, this error does not occur and synchronization can be started. 

![024-11-10_dokuwiki_1731254555](https://github.com/user-attachments/assets/90164d3f-0471-4ff0-bb2e-ba368cdd40e2)

However, then again this same error is visible:

![024-11-10_dokuwiki_1731254562](https://github.com/user-attachments/assets/d57de7d0-c11b-4263-8afe-e7f179484362)

Logs:

![024-11-10_dokuwiki_1731254569](https://github.com/user-attachments/assets/86bd9edd-9b3e-40ea-b3db-7662d97ec599)

```
2024-11-10 15:17:07E_WARNING: Undefined array key "startsync"/var/www/html/wiki/lib/plugins/sync/admin.php(145)
    #0 /var/www/html/wiki/lib/plugins/sync/admin.php(145): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/html/wiki/inc/template.php(205): admin_plugin_sync->html()
    #2 /var/www/html/wiki/inc/Action/Admin.php(43): tpl_admin()
    #3 /var/www/html/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
    #4 [internal function]: tpl_content_core()
    #5 /var/www/html/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #6 /var/www/html/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #7 /var/www/html/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #8 /var/www/html/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
    #9 /var/www/html/wiki/inc/actions.php(30): include('...')
    #10 /var/www/html/wiki/doku.php(131): act_dispatch()
    #11 {main}
2024-11-10 15:17:07E_WARNING: Undefined array key "ltime"/var/www/html/wiki/lib/plugins/sync/admin.php(324)
    #0 /var/www/html/wiki/lib/plugins/sync/admin.php(324): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/html/wiki/lib/plugins/sync/admin.php(188): admin_plugin_sync->_profileform()
    #2 /var/www/html/wiki/inc/template.php(205): admin_plugin_sync->html()
    #3 /var/www/html/wiki/inc/Action/Admin.php(43): tpl_admin()
    #4 /var/www/html/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
    #5 [internal function]: tpl_content_core()
    #6 /var/www/html/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #7 /var/www/html/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #8 /var/www/html/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #9 /var/www/html/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
    #10 /var/www/html/wiki/inc/actions.php(30): include('...')
    #11 /var/www/html/wiki/doku.php(131): act_dispatch()
    #12 {main}
2024-11-10 15:17:29E_WARNING: Undefined array key "sync_pages"/var/www/html/wiki/lib/plugins/sync/admin.php(110)
    #0 /var/www/html/wiki/lib/plugins/sync/admin.php(110): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/html/wiki/inc/template.php(205): admin_plugin_sync->html()
    #2 /var/www/html/wiki/inc/Action/Admin.php(43): tpl_admin()
    #3 /var/www/html/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
    #4 [internal function]: tpl_content_core()
    #5 /var/www/html/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #6 /var/www/html/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #7 /var/www/html/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #8 /var/www/html/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
    #9 /var/www/html/wiki/inc/actions.php(30): include('...')
    #10 /var/www/html/wiki/doku.php(131): act_dispatch()
    #11 {main}
2024-11-10 15:17:29E_WARNING: Undefined array key "sync_media"/var/www/html/wiki/lib/plugins/sync/admin.php(110)
    #0 /var/www/html/wiki/lib/plugins/sync/admin.php(110): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/html/wiki/inc/template.php(205): admin_plugin_sync->html()
    #2 /var/www/html/wiki/inc/Action/Admin.php(43): tpl_admin()
    #3 /var/www/html/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
    #4 [internal function]: tpl_content_core()
    #5 /var/www/html/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #6 /var/www/html/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #7 /var/www/html/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #8 /var/www/html/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
    #9 /var/www/html/wiki/inc/actions.php(30): include('...')
    #10 /var/www/html/wiki/doku.php(131): act_dispatch()
    #11 {main}
2024-11-10 15:17:29E_WARNING: Undefined array key "startsync"/var/www/html/wiki/lib/plugins/sync/admin.php(145)
    #0 /var/www/html/wiki/lib/plugins/sync/admin.php(145): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/html/wiki/inc/template.php(205): admin_plugin_sync->html()
    #2 /var/www/html/wiki/inc/Action/Admin.php(43): tpl_admin()
    #3 /var/www/html/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
    #4 [internal function]: tpl_content_core()
    #5 /var/www/html/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #6 /var/www/html/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #7 /var/www/html/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #8 /var/www/html/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
    #9 /var/www/html/wiki/inc/actions.php(30): include('...')
    #10 /var/www/html/wiki/doku.php(131): act_dispatch()
    #11 {main}
2024-11-10 15:17:29E_WARNING: Undefined array key "ltime"/var/www/html/wiki/lib/plugins/sync/admin.php(324)
    #0 /var/www/html/wiki/lib/plugins/sync/admin.php(324): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/html/wiki/lib/plugins/sync/admin.php(188): admin_plugin_sync->_profileform()
    #2 /var/www/html/wiki/inc/template.php(205): admin_plugin_sync->html()
    #3 /var/www/html/wiki/inc/Action/Admin.php(43): tpl_admin()
    #4 /var/www/html/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
    #5 [internal function]: tpl_content_core()
    #6 /var/www/html/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #7 /var/www/html/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #8 /var/www/html/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #9 /var/www/html/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
    #10 /var/www/html/wiki/inc/actions.php(30): include('...')
    #11 /var/www/html/wiki/doku.php(131): act_dispatch()
    #12 {main}
2024-11-10 15:17:52E_WARNING: Undefined array key "no"/var/www/html/wiki/lib/plugins/sync/admin.php(20)
    #0 /var/www/html/wiki/lib/plugins/sync/admin.php(20): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/html/wiki/inc/Extension/PluginController.php(130): admin_plugin_sync->__construct()
    #2 /var/www/html/wiki/inc/pluginutils.php(55): dokuwiki\Extension\PluginController->load()
    #3 /var/www/html/wiki/inc/Ui/Admin.php(134): plugin_load()
    #4 /var/www/html/wiki/inc/Ui/Admin.php(32): dokuwiki\Ui\Admin->getPluginList()
    #5 /var/www/html/wiki/inc/template.php(208): dokuwiki\Ui\Admin->show()
    #6 /var/www/html/wiki/inc/Action/Admin.php(43): tpl_admin()
    #7 /var/www/html/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
    #8 [internal function]: tpl_content_core()
    #9 /var/www/html/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #10 /var/www/html/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #11 /var/www/html/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #12 /var/www/html/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
    #13 /var/www/html/wiki/inc/actions.php(30): include('...')
    #14 /var/www/html/wiki/doku.php(131): act_dispatch()
    #15 {main}
```

Deprecated warnings:

![024-11-10_dokuwiki_1731254549](https://github.com/user-attachments/assets/0648b439-8f9d-426f-a99d-30bfd3829329)

**Comment by eduardomozart** [comment]
I figure out that using the refactory branch with bugfixes applied (https://github.com/splitbrain/dokuwiki-plugin-sync/pull/74) does make the migration more stable. This issue still occurs to me, but less than before, at least I'm able to sync my Wikis. One is running PHP 8 (the wiki with the remote plugin) and the other one is running PHP 7.4 (the remote wiki).

**Comment by Juergen-Vollmer** [comment]
Hi everybody

is there a fix for that error?
    "transport error - Premature End of File (.."
I use PHP 8.2 in the local and remote wiki and the actual docuwiki

With best regards
Jürgen
